from graph import Graph, Vertex

#Create graph
underground = Graph()        

#Create vertices
acton_town = Vertex(["Acton Town", ["District", "Piccadilly"]])
aldgate = Vertex(["Aldgate", ["Circle", "Metropolitan"]])
aldgate_east = Vertex(["Aldgate East", ["District", "Hammersmith and City"]])
alperton = Vertex(["Alperton", ["Piccadilly"]])
amersham = Vertex(["Amersham", ["Metropolitan"]])
angel = Vertex(["Angel", ["Northern"]])
archway = Vertex(["Archway", ["Northern"]])
arnos_grove = Vertex(["Arnos Grove", ["Piccadilly"]])
arsenal = Vertex(["Arsenal", ["Piccadilly"]])
baker_street = Vertex(["Baker Street", ["Bakerloo", "Circle", "Hammersmith and City", "Jubilee", "Metropolitan"]])
balham = Vertex(["Balham", ["Northern"]])
bank = Vertex(["Bank", ["Central", "Northern", "Waterloo and City"]])
barbican = Vertex(["Barbican", ["Circle", "Hammersmith and City", "Metropolitan"]])
barking = Vertex(["Barking", ["District", "Hammersmith and City"]])
barkingside = Vertex(["Barkingside", ["Central"]])
barons_court = Vertex(["Barons Court", ["District", "Piccadilly"]])
battersea_power_station = Vertex(["Battersea Power Station", ["Northern"]])
bayswater = Vertex(["Bayswater", ["Circle", "District"]])
becontree = Vertex(["Becontree", ["District"]])
belsize_park = Vertex(["Belsize Park", ["Northern"]])
bermondsey = Vertex(["Bermondsey", ["Jubilee"]])
bethnal_green = Vertex(["Bethnal Green", ["Central"]])
blackhorse_road = Vertex(["Blackhorse Road", ["Victoria"]])
blackfriars = Vertex(["Blackfriars", ["Circle", "District"]])
bond_street = Vertex(["Bond Street", ["Central", "Jubilee"]])
boston_manor = Vertex(["Boston Manor", ["Piccadilly"]])
bounds_green = Vertex(["Bounds Green", ["Piccadilly"]])
bow_road = Vertex(["Bow Road", ["District", "Hammersmith and City"]])
borough = Vertex(["Borough", ["Northern"]])
brent_cross = Vertex(["Brent Cross", ["Northern"]])
brixton = Vertex(["Brixton", ["Victoria"]])
bromley_by_bow = Vertex(["Bromley-by-Bow", ["District", "Hammersmith and City"]])
buckhurst_hill = Vertex(["Buckhurst Hill", ["Central"]])
burnt_oak = Vertex(["Burnt Oak", ["Northern"]])
caledonian_road = Vertex(["Caledonian Road", ["Piccadilly"]])
camden_town = Vertex(["Camden Town", ["Northern"]])
canada_water = Vertex(["Canada Water", ["Jubilee"]])
canary_wharf = Vertex(["Canary Wharf", ["Jubilee"]])
canons_park = Vertex(["Canons Park", ["Jubilee"]])
canning_town = Vertex(["Canning Town", ["Jubilee"]])
cannon_street = Vertex(["Cannon Street", ["Circle", "District"]])
chalfont_and_latimer = Vertex(["Chalfont and Latimer", ["Metropolitan"]])
chalk_farm = Vertex(["Chalk Farm", ["Northern"]])
chancery_lane = Vertex(["Chancery Lane", ["Central"]])
charing_cross = Vertex(["Charing Cross", ["Bakerloo", "Northern"]])
chesham = Vertex(["Chesham", ["Metropolitan"]])
chigwell = Vertex(["Chigwell", ["Central"]])
chiswick_park = Vertex(["Chiswick Park", ["District"]])
chorleywood = Vertex(["Chorleywood", ["Metropolitan"]])
clapham_common = Vertex(["Clapham Common", ["Northern"]])
clapham_north = Vertex(["Clapham North", ["Northern"]])
clapham_south = Vertex(["Clapham South", ["Northern"]])
colindale = Vertex(["Colindale", ["Northern"]])
colliers_wood = Vertex(["Colliers Wood", ["Northern"]])
cockfosters = Vertex(["Cockfosters", ["Piccadilly"]])
covent_garden = Vertex(["Covent Garden", ["Piccadilly"]])
croxley = Vertex(["Croxley", ["Metropolitan"]])
dagenham_east = Vertex(["Dagenham East", ["District"]])
dagenham_heathway = Vertex(["Dagenham Heathway", ["District"]])
debden = Vertex(["Debden", ["Central"]])
dollis_hill = Vertex(["Dollis Hill", ["Jubilee"]])
ealing_broadway = Vertex(["Ealing Broadway", ["Central", "District"]])
ealing_common = Vertex(["Ealing Common", ["District"]])
earls_court = Vertex(["Earl's Court", ["District", "Piccadilly"]])
eastcoate = Vertex(["Eastcoate", ["Metropolitan", "Piccadilly"]])
east_acton = Vertex(["East Acton", ["Central"]])
east_finchley = Vertex(["East Finchley", ["Northern"]])
east_ham = Vertex(["East Ham", ["District", "Hammersmith and City"]])
east_putney = Vertex(["East Putney", ["District"]])
edgware = Vertex(["Edgware", ["Northern"]])
edgware_road = Vertex(["Edgware Road", ["Bakerloo", "Circle", "District", "Hammersmith and City"]])
elephant_and_castle = Vertex(["Elephant and Castle", ["Bakerloo", "Northern"]])
elm_park = Vertex(["Elm Park", ["District"]])
embankment = Vertex(["Embankment", ["Bakerloo", "Circle", "District", "Northern"]])
epping = Vertex(["Epping", ["Central"]])
euston = Vertex(["Euston", ["Northern", "Victoria"]])
euston_square = Vertex(["Euston Square", ["Circle", "Hammersmith and City", "Metropolitan"]])
fairlop = Vertex(["Fairlop", ["Central"]])
farringdon = Vertex(["Farringdon", ["Circle", "Hammersmith and City", "Metropolitan"]])
finchley_central = Vertex(["Finchley Central", ["Northern"]])
finchley_road = Vertex(["Finchley Road", ["Jubilee", "Metropolitan"]])
finsbury_park = Vertex(["Finsbury Park", ["Piccadilly", "Victoria"]])
fulham_broadway = Vertex(["Fulham Broadway", ["District"]])
gants_hill = Vertex(["Gant's Hill", ["Central"]])
gloucester_road = Vertex(["Gloucester Road", ["Circle", "District", "Piccadilly"]])
golders_green = Vertex(["Golders Green", ["Northern"]])
goldhawk_road = Vertex(["Goldhawk Road", ["Circle", "Hammersmith and City"]])
goodge_street = Vertex(["Goodge Street", ["Northern"]])
grange_hill = Vertex(["Grange Hill", ["Central"]])
great_portland_street = Vertex(["Great Portland Street", ["Circle", "Hammersmith and City", "Metropolitan"]])
green_park = Vertex(["Green Park", ["Jubilee", "Piccadilly", "Victoria"]])
greenford = Vertex(["Greenford", ["Central"]])
gunnersby = Vertex(["Gunnersby", ["District"]])
hainault = Vertex(["Hainault", ["Central"]])
hammersmith = Vertex(["Hammersmith", ["Circle", "District", "Hammersmith and City", "Piccadilly"]])
hampstead = Vertex(["Hampstead", ["Northern"]])
hanger_lane = Vertex(["Hanger Lane", ["Central"]])
harlesden = Vertex(["Harlesden", ["Bakerloo"]])
harrow_on_the_hill = Vertex(["Harrow-on-the-Hill", ["Metropolitan"]])
harrow_and_wealdstone = Vertex(["Harrow and Wealdstone", ["Bakerloo"]])
hatton_cross = Vertex(["Hatton Cross", ["Piccadilly"]])
heathrow_terminals_2_and_3 = Vertex(["Heathrow Terminals 2 and 3", ["Piccadilly"]])
heathrow_terminal_4 = Vertex(["Heathrow Terminal 4", ["Piccadilly"]])
heathrow_terminal_5 = Vertex(["Heathrow Terminal 5", ["Piccadilly"]])
hendon_central = Vertex(["Hendon Central", ["Northern"]])
high_barnet = Vertex(["High Barnet", ["Northern"]])
high_street_kensington = Vertex(["High Street Kensington", ["Circle", "District"]])
highbury_and_islington = Vertex(["Highbury and Islington", ["Victoria"]])
highgate = Vertex(["Highgate", ["Northern"]])
hillingdon = Vertex(["Hillingdon", ["Metropolitan", "Piccadilly"]])
holborn = Vertex(["Holborn", ["Central", "Piccadilly"]])
holland_park = Vertex(["Holland Park", ["Central"]])
holloway_road = Vertex(["Holloway Road", ["Piccadilly"]])
hornchurch = Vertex(["Hornchurch", ["District"]])
hounslow_central = Vertex(["Hounslow Central", ["Piccadilly"]])
hounslow_east = Vertex(["Hounslow East", ["Piccadilly"]])
hounslow_west = Vertex(["Hounslow West", ["Piccadilly"]])
hyde_park_corner = Vertex(["Hyde Park Corner", ["Piccadilly"]])
ickenham = Vertex(["Ickenham", ["Metropolitan", "Piccadilly"]])
kennington = Vertex(["Kennington", ["Northern"]])
kensal_green = Vertex(["Kensal Green", ["Bakerloo"]])
kensington_olympia = Vertex(["Kensington Olympia", ["District"]])
kentish_town = Vertex(["Kentish Town", ["Northern"]])
kenton = Vertex(["Kenton", ["Bakerloo"]])
kew_gardens = Vertex(["Kew Gardens", ["District"]])
kilburn = Vertex(["Kilburn", ["Jubilee"]])
kilburn_park = Vertex(["Kilburn Park", ["Bakerloo"]])
kingsbury = Vertex(["Kingsbury", ["Jubilee"]])
kings_cross_st_pancras = Vertex(["King's Cross St Pancras", ["Circle", "Hammersmith and City", "Metropolitan", "Northern", "Piccadilly", "Victoria"]])
knightsbridge = Vertex(["Knightsbridge", ["Piccadilly"]])
ladbroke_grove = Vertex(["Ladbroke Grove", ["Circle", "Hammersmith and City"]])
lambeth_north = Vertex(["Lambeth North", ["Bakerloo"]])
lancaster_gate = Vertex(["Lancaster Gate", ["Central"]])
latimer_road = Vertex(["Latimer Road", ["Circle", "Hammersmith and City"]])
leicester_square = Vertex(["Leicester Square", ["Northern", "Piccadilly"]])
leyton = Vertex(["Leyton", ["Central"]])
leytonstone = Vertex(["Leytonstone", ["Central"]])
liverpool_street = Vertex(["Liverpool Street", ["Central", "Circle", "Hammersmith and City", "Metropolitan"]])
london_bridge = Vertex(["London Bridge", ["Jubilee", "Northern"]])
loughton = Vertex(["Loughton", ["Central"]])
maida_vale = Vertex(["Maida Vale", ["Bakerloo"]])
manor_house = Vertex(["Manor House", ["Piccadilly"]])
mansion_house = Vertex(["Mansion House", ["Circle", "District"]])
marble_arch = Vertex(["Marble Arch", ["Central"]])
marylebone = Vertex(["Marylebone", ["Bakerloo"]])
mile_end = Vertex(["Mile End", ["Central", "District", "Hammersmith and City"]])
mill_hill_east = Vertex(["Mill Hill East", ["Northern"]])
monument = Vertex(["Monument", ["Circle", "District"]])
moorgate = Vertex(["Moorgate", ["Circle", "Hammersmith and City", "Metropolitan", "Northern"]])
moor_park = Vertex(["Moor Park", ["Metropolitan"]])
morden = Vertex(["Morden", ["Northern"]])
mornington_crescent = Vertex(["Mornington Crescent", ["Northern"]])
neasden = Vertex(["Neasden", ["Jubilee"]])
newbury_park = Vertex(["Newbury Park", ["Central"]])
nine_elms = Vertex(["Nine Elms", ["Northern"]])
north_acton = Vertex(["North Acton", ["Central"]])
north_ealing = Vertex(["North Ealing", ["Piccadilly"]])
north_greenwich = Vertex(["North Greenwich", ["Jubilee"]])
north_harrow = Vertex(["North Harrow", ["Metropolitan"]])
north_wembley = Vertex(["North Wembley", ["Bakerloo"]])
northfields = Vertex(["Northfields", ["Piccadilly"]])
northolt = Vertex(["Northolt", ["Central"]])
northwick_park = Vertex(["Northwick Park", ["Metropolitan"]])
northwood = Vertex(["Northwood", ["Metropolitan"]])
northwood_hills = Vertex(["Northwood Hills", ["Metropolitan"]])
notting_hill_gate = Vertex(["Notting Hill Gate", ["Central", "Circle", "District"]])
oakwood = Vertex(["Oakwood", ["Piccadilly"]])
old_street = Vertex(["Old Street", ["Northern"]])
osterley = Vertex(["Osterley", ["Piccadilly"]])
oval = Vertex(["Oval", ["Northern"]])
oxford_circus = Vertex(["Oxford Circus", ["Bakerloo", "Central", "Victoria"]])
paddington = Vertex(["Paddington", ["Bakerloo", "Circle", "District", "Hammersmith and City"]])
park_royal = Vertex(["Park Royal", ["Piccadilly"]])
parsons_green = Vertex(["Parsons Green", ["District"]])
perivale = Vertex(["Perivale", ["Central"]])
piccadilly_circus = Vertex(["Piccadilly Circus", ["Bakerloo", "Piccadilly"]])
pimlico = Vertex(["Pimlico", ["Victoria"]])
pinner = Vertex(["Pinner", ["Metropolitan"]])
plaistow = Vertex(["Plaistow", ["District", "Hammersmith and City"]])
preston_road = Vertex(["Preston Road", ["Metropolitan"]])
putney_bridge = Vertex(["Putney Bridge", ["District"]])
queens_park = Vertex(["Queen's Park", ["Bakerloo"]])
queensbury = Vertex(["Queensbury", ["Jubilee"]])
queensway = Vertex(["Queensway", ["Central"]])
ravenscourt_park = Vertex(["Ravenscourt Park", ["District"]])
rayners_lane = Vertex(["Rayners Lane", ["Metropolitan", "Piccadilly"]])
regents_park = Vertex(["Regent's Park", ["Bakerloo"]])
redbridge = Vertex(["Redbridge", ["Central"]])
richmond = Vertex(["Richmond", ["District"]])
rickmansworth = Vertex(["Rickmansworth", ["Metropolitan"]])
roding_valley = Vertex(["Roding Valley", ["Central"]])
royal_oak = Vertex(["Royal Oak", ["Circle", "Hammersmith and City"]])
ruislip = Vertex(["Ruislip", ["Metropolitan", "Piccadilly"]])
ruislip_gardens = Vertex(["Ruislip Gardens", ["Central"]])
ruislip_manor = Vertex(["Ruislip Manor", ["Metropolitan", "Piccadilly"]])
russell_square = Vertex(["Russell Square", ["Piccadilly"]])
seven_sisters = Vertex(["Seven Sisters", ["Victoria"]])
shepherds_bush = Vertex(["Shepherd's Bush", ["Central"]])
sheperds_bush_market = Vertex(["Shepherd's Bush Market", ["Circle", "Hammersmith and City"]])
sloane_square = Vertex(["Sloane Square", ["Circle", "District"]])
snaresbrook = Vertex(["Snaresbrook", ["Central"]])
south_ealing = Vertex(["South Ealing", ["Piccadilly"]])
south_harrow = Vertex(["South Harrow", ["Piccadilly"]])
south_kensington = Vertex(["South Kensington", ["Circle", "District", "Piccadilly"]])
south_kenton = Vertex(["South Kenton", ["Bakerloo"]])
south_ruislip = Vertex(["South Ruislip", ["Central"]])
south_wimbeldon = Vertex(["South Wimbeldon", ["Northern"]])
south_woodford = Vertex(["South Woodford", ["Central"]])
southfields = Vertex(["Southfields", ["District"]])
southgate = Vertex(["Southgate", ["Piccadilly"]])
southwark = Vertex(["Southwark", ["Jubilee"]])
stamford_brook = Vertex(["Stamford Brook", ["District"]])
stanmore = Vertex(["Stanmore", ["Jubilee"]])
stepney_green = Vertex(["Stepney Green", ["District", "Hammersmith and City"]])
st_james_park = Vertex(["St James's Park", ["Circle", "District"]])
st_johns_wood = Vertex(["St John's Wood", ["Jubilee"]])
st_pauls = Vertex(["St Paul's", ["Central"]])
stockwell = Vertex(["Stockwell", ["Northern", "Victoria"]])
stonebridge_park = Vertex(["Stonebridge Park", ["Bakerloo"]])
stratford = Vertex(["Stratford", ["Central","Jubilee"]])
sudbury_hill = Vertex(["Sudbury Hill", ["Piccadilly"]])
sudbury_town = Vertex(["Sudbury Town", ["Piccadilly"]])
swiss_cottage = Vertex(["Swiss Cottage", ["Jubilee"]])
temple = Vertex(["Temple", ["Circle", "District"]])
theydon_bois = Vertex(["Theydon Bois", ["Central"]])
tooting_bec = Vertex(["Tooting Bec", ["Northern"]])
tooting_broadway = Vertex(["Tooting Broadway", ["Northern"]])
tottenham_court_road = Vertex(["Tottenham Court Road", ["Central", "Northern"]])
tottenham_hale = Vertex(["Tottenham Hale", ["Victoria"]])
totteridge_and_whetstone = Vertex(["Totteridge and Whetstone", ["Northern"]])
tower_hill = Vertex(["Tower Hill", ["Circle", "District"]])
tufnell_park = Vertex(["Tufnell Park", ["Northern"]])
turnham_green = Vertex(["Turnham Green", ["District", "Piccadilly"]])
turnpike_lane = Vertex(["Turnpike Lane", ["Piccadilly"]])
upminster = Vertex(["Upminster", ["District"]])
upminster_bridge = Vertex(["Upminster Bridge", ["District"]])
upney = Vertex(["Upney", ["District"]])
upton_park = Vertex(["Upton Park", ["District", "Hammersmith and City"]])
uxbridge = Vertex(["Uxbridge", ["Metropolitan", "Piccadilly"]])
vauxhall = Vertex(["Vauxhall", ["Victoria"]])
victoria = Vertex(["Victoria", ["Circle", "District", "Victoria"]])
walthamstow_central = Vertex(["Walthamstow Central", ["Victoria"]])
wanstead = Vertex(["Wanstead", ["Central"]])
warren_street = Vertex(["Warren Street", ["Victoria"]])
warwick_avenue = Vertex(["Warwick Avenue", ["Bakerloo"]])
waterloo = Vertex(["Waterloo", ["Bakerloo", "Jubilee", "Northern", "Waterloo and City"]])
watford = Vertex(["Watford", ["Metropolitan"]])
wembley_central = Vertex(["Wembley Central", ["Bakerloo"]])
wembley_park = Vertex(["Wembley Park", ["Jubilee", "Metropolitan"]])
west_acton = Vertex(["West Acton", ["Central"]])
west_brompton = Vertex(["West Brompton", ["District"]])
west_finchley = Vertex(["West Finchley", ["Northern"]])
west_ham = Vertex(["West Ham", ["District", "Hammersmith and City", "Jubilee"]])
west_harrow = Vertex(["West Harrow", ["Metropolitan"]])
west_hampstead = Vertex(["West Hampstead", ["Jubilee"]])
west_kensington = Vertex(["West Kensington", ["District"]])
west_ruislip = Vertex(["West Ruislip", ["Central"]])
westbourne_park = Vertex(["Westbourne Park", ["Circle", "Hammersmith and City"]])
westminster = Vertex(["Westminster", ["Circle", "District", "Jubilee"]])
white_city = Vertex(["White City", ["Central"]])
whitechapel = Vertex(["Whitechapel", ["District", "Hammersmith and City"]])
willesden_green = Vertex(["Willesden Green", ["Jubilee"]])
willesden_junction = Vertex(["Willesden Junction", ["Bakerloo"]])
wimbeldon = Vertex(["Wimbeldon", ["District"]])
wimbeldon_park = Vertex(["Wimbeldon Park", ["District"]])
wood_green = Vertex(["Wood Green", ["Piccadilly"]])
wood_lane = Vertex(["Wood Lane", ["Circle", "Hammersmith and City"]])
woodford = Vertex(["Woodford", ["Central"]])
woodside_park = Vertex(["Woodside Park", ["Northern"]])

#Add vertices to graph
underground.add_vertex(acton_town)
underground.add_vertex(aldgate)
underground.add_vertex(aldgate_east)
underground.add_vertex(alperton)
underground.add_vertex(amersham)
underground.add_vertex(angel)
underground.add_vertex(archway)
underground.add_vertex(arnos_grove)
underground.add_vertex(arsenal)
underground.add_vertex(baker_street)
underground.add_vertex(balham)
underground.add_vertex(bank)
underground.add_vertex(barbican)
underground.add_vertex(barking)
underground.add_vertex(barkingside)
underground.add_vertex(barons_court)
underground.add_vertex(battersea_power_station)
underground.add_vertex(bayswater)
underground.add_vertex(becontree)
underground.add_vertex(belsize_park)
underground.add_vertex(bermondsey)
underground.add_vertex(bethnal_green)
underground.add_vertex(blackfriars)
underground.add_vertex(blackhorse_road)
underground.add_vertex(bond_street)
underground.add_vertex(borough)
underground.add_vertex(bounds_green)
underground.add_vertex(boston_manor)
underground.add_vertex(bow_road)
underground.add_vertex(brent_cross)
underground.add_vertex(bromley_by_bow)
underground.add_vertex(brixton)
underground.add_vertex(buckhurst_hill)
underground.add_vertex(burnt_oak)
underground.add_vertex(caledonian_road)
underground.add_vertex(camden_town)
underground.add_vertex(canada_water)
underground.add_vertex(canary_wharf)
underground.add_vertex(canning_town)
underground.add_vertex(cannon_street)
underground.add_vertex(canons_park)
underground.add_vertex(chalk_farm)
underground.add_vertex(chesham)
underground.add_vertex(chalfont_and_latimer)
underground.add_vertex(chancery_lane)
underground.add_vertex(charing_cross)
underground.add_vertex(chigwell)
underground.add_vertex(chiswick_park)
underground.add_vertex(chorleywood)
underground.add_vertex(clapham_north)
underground.add_vertex(clapham_common)
underground.add_vertex(clapham_south)
underground.add_vertex(cockfosters)
underground.add_vertex(colindale)
underground.add_vertex(colliers_wood)
underground.add_vertex(covent_garden)
underground.add_vertex(croxley)
underground.add_vertex(dagenham_east)
underground.add_vertex(dagenham_heathway)
underground.add_vertex(debden)
underground.add_vertex(dollis_hill)
underground.add_vertex(ealing_broadway)
underground.add_vertex(ealing_common)
underground.add_vertex(earls_court)
underground.add_vertex(eastcoate)
underground.add_vertex(east_acton)
underground.add_vertex(east_finchley)
underground.add_vertex(east_ham)
underground.add_vertex(east_putney)
underground.add_vertex(edgware)
underground.add_vertex(edgware_road)
underground.add_vertex(elephant_and_castle)
underground.add_vertex(elm_park)
underground.add_vertex(embankment)
underground.add_vertex(epping)
underground.add_vertex(euston)
underground.add_vertex(euston_square)
underground.add_vertex(fairlop)
underground.add_vertex(farringdon)
underground.add_vertex(finchley_central)
underground.add_vertex(finchley_road)
underground.add_vertex(finsbury_park)
underground.add_vertex(fulham_broadway)
underground.add_vertex(gants_hill)
underground.add_vertex(gloucester_road)
underground.add_vertex(golders_green)
underground.add_vertex(goldhawk_road)
underground.add_vertex(goodge_street)
underground.add_vertex(grange_hill)
underground.add_vertex(great_portland_street)
underground.add_vertex(green_park)
underground.add_vertex(greenford)
underground.add_vertex(gunnersby)
underground.add_vertex(hainault)
underground.add_vertex(hammersmith)
underground.add_vertex(hampstead)
underground.add_vertex(hanger_lane)
underground.add_vertex(harlesden)
underground.add_vertex(harrow_and_wealdstone)
underground.add_vertex(harrow_on_the_hill)
underground.add_vertex(hatton_cross)
underground.add_vertex(heathrow_terminals_2_and_3)
underground.add_vertex(heathrow_terminal_4)
underground.add_vertex(heathrow_terminal_5)
underground.add_vertex(hendon_central)
underground.add_vertex(high_barnet)
underground.add_vertex(high_street_kensington)
underground.add_vertex(highbury_and_islington)
underground.add_vertex(highgate)
underground.add_vertex(hillingdon)
underground.add_vertex(holborn)
underground.add_vertex(holland_park)
underground.add_vertex(holloway_road)
underground.add_vertex(hornchurch)
underground.add_vertex(hounslow_central)
underground.add_vertex(hounslow_east)
underground.add_vertex(hounslow_west)
underground.add_vertex(hyde_park_corner)
underground.add_vertex(ickenham)
underground.add_vertex(kennington)
underground.add_vertex(kensal_green)
underground.add_vertex(kensington_olympia)
underground.add_vertex(kentish_town)
underground.add_vertex(kenton)
underground.add_vertex(kew_gardens)
underground.add_vertex(kilburn)
underground.add_vertex(kilburn_park)
underground.add_vertex(kingsbury)
underground.add_vertex(kings_cross_st_pancras)
underground.add_vertex(knightsbridge)
underground.add_vertex(ladbroke_grove)
underground.add_vertex(lambeth_north)
underground.add_vertex(lancaster_gate)
underground.add_vertex(latimer_road)
underground.add_vertex(leicester_square)
underground.add_vertex(leyton)
underground.add_vertex(leytonstone)
underground.add_vertex(liverpool_street)
underground.add_vertex(london_bridge)
underground.add_vertex(loughton)
underground.add_vertex(mile_end)
underground.add_vertex(mill_hill_east)
underground.add_vertex(maida_vale)
underground.add_vertex(manor_house)
underground.add_vertex(mansion_house)
underground.add_vertex(marble_arch)
underground.add_vertex(marylebone)
underground.add_vertex(moor_park)
underground.add_vertex(moorgate)
underground.add_vertex(monument)
underground.add_vertex(morden)
underground.add_vertex(mornington_crescent)
underground.add_vertex(neasden)
underground.add_vertex(newbury_park)
underground.add_vertex(nine_elms)
underground.add_vertex(north_acton)
underground.add_vertex(north_ealing)
underground.add_vertex(north_harrow)
underground.add_vertex(northfields)
underground.add_vertex(northolt)
underground.add_vertex(northwick_park)
underground.add_vertex(northwood)
underground.add_vertex(north_greenwich)
underground.add_vertex(north_wembley)
underground.add_vertex(northwood_hills)
underground.add_vertex(notting_hill_gate)
underground.add_vertex(oakwood)
underground.add_vertex(old_street)
underground.add_vertex(osterley)
underground.add_vertex(oxford_circus)
underground.add_vertex(oval)
underground.add_vertex(paddington)
underground.add_vertex(park_royal)
underground.add_vertex(parsons_green)
underground.add_vertex(perivale)
underground.add_vertex(piccadilly_circus)
underground.add_vertex(pimlico)
underground.add_vertex(pinner)
underground.add_vertex(plaistow)
underground.add_vertex(preston_road)
underground.add_vertex(putney_bridge)
underground.add_vertex(queensbury)
underground.add_vertex(queensway)
underground.add_vertex(queens_park)
underground.add_vertex(ravenscourt_park)
underground.add_vertex(rayners_lane)
underground.add_vertex(redbridge)
underground.add_vertex(regents_park)
underground.add_vertex(richmond)
underground.add_vertex(rickmansworth)
underground.add_vertex(roding_valley)
underground.add_vertex(royal_oak)
underground.add_vertex(ruislip)
underground.add_vertex(ruislip_gardens)
underground.add_vertex(ruislip_manor)
underground.add_vertex(russell_square)
underground.add_vertex(seven_sisters)
underground.add_vertex(shepherds_bush)
underground.add_vertex(sheperds_bush_market)
underground.add_vertex(sloane_square)
underground.add_vertex(snaresbrook)
underground.add_vertex(south_ealing)
underground.add_vertex(stamford_brook)
underground.add_vertex(stepney_green)
underground.add_vertex(st_pauls)
underground.add_vertex(southwark)
underground.add_vertex(south_harrow)
underground.add_vertex(south_kenton)
underground.add_vertex(south_kensington)
underground.add_vertex(south_ruislip)
underground.add_vertex(south_woodford)
underground.add_vertex(south_wimbeldon)
underground.add_vertex(southfields)
underground.add_vertex(southgate)
underground.add_vertex(stanmore)
underground.add_vertex(stockwell)
underground.add_vertex(stonebridge_park)
underground.add_vertex(stratford)
underground.add_vertex(st_james_park)
underground.add_vertex(st_johns_wood)
underground.add_vertex(sudbury_hill)
underground.add_vertex(sudbury_town)
underground.add_vertex(swiss_cottage)
underground.add_vertex(temple)
underground.add_vertex(theydon_bois)
underground.add_vertex(tooting_bec)
underground.add_vertex(tooting_broadway)
underground.add_vertex(tottenham_court_road)
underground.add_vertex(tottenham_hale)
underground.add_vertex(totteridge_and_whetstone)
underground.add_vertex(tower_hill)
underground.add_vertex(tufnell_park)
underground.add_vertex(turnham_green)
underground.add_vertex(turnpike_lane)
underground.add_vertex(upminster)
underground.add_vertex(upminster_bridge)
underground.add_vertex(upney)
underground.add_vertex(upton_park)
underground.add_vertex(uxbridge)
underground.add_vertex(vauxhall)
underground.add_vertex(victoria)
underground.add_vertex(walthamstow_central)
underground.add_vertex(wanstead)
underground.add_vertex(warren_street)
underground.add_vertex(warwick_avenue)
underground.add_vertex(waterloo)
underground.add_vertex(watford)
underground.add_vertex(wembley_central)
underground.add_vertex(wembley_park)
underground.add_vertex(west_acton)
underground.add_vertex(west_brompton)
underground.add_vertex(west_finchley)
underground.add_vertex(west_ham)
underground.add_vertex(west_hampstead)
underground.add_vertex(west_harrow)
underground.add_vertex(west_kensington)
underground.add_vertex(west_ruislip)
underground.add_vertex(westbourne_park)
underground.add_vertex(westminster)
underground.add_vertex(white_city)
underground.add_vertex(whitechapel)
underground.add_vertex(willesden_green)
underground.add_vertex(willesden_junction)
underground.add_vertex(wimbeldon)
underground.add_vertex(wimbeldon_park)
underground.add_vertex(wood_green)
underground.add_vertex(wood_lane)
underground.add_vertex(woodford)
underground.add_vertex(woodside_park)

#Add edges
underground.add_edge(acton_town, ealing_common, ["District", "Piccadilly"], 2)
underground.add_edge(acton_town, south_ealing, ["Piccadilly"], 3)
underground.add_edge(aldgate, tower_hill, ["Circle"], 2)
underground.add_edge(aldgate_east, tower_hill, ["District"], 3)
underground.add_edge(alperton, sudbury_town, ["Piccadilly"], 3)
underground.add_edge(amersham, chalfont_and_latimer, ["Metropolitan"], 4)
underground.add_edge(angel, old_street, ["Northern"], 3)
underground.add_edge(archway, tufnell_park, ["Northern"], 2)
underground.add_edge(arnos_grove, bounds_green, ["Piccadilly"], 2)
underground.add_edge(arsenal, holloway_road, ["Piccadilly"], 2)
underground.add_edge(baker_street, great_portland_street, ["Circle", "Hammersmith and City", "Metropolitan"], 2)
underground.add_edge(baker_street, bond_street, ["Jubilee"], 2)
underground.add_edge(baker_street, regents_park, ["Bakerloo"], 2)
underground.add_edge(balham, tooting_bec, ["Northern"], 2)
underground.add_edge(bank, liverpool_street, ["Central"], 2)
underground.add_edge(bank, waterloo, ["Waterloo and City"], 5)
underground.add_edge(bank, london_bridge, ["Northern"], 2)
underground.add_edge(barbican, moorgate, ["Circle", "Hammersmith and City", "Metropolitan"], 2)
underground.add_edge(barking, east_ham, ["District", "Hammersmith and City"], 4)
underground.add_edge(barkingside, fairlop, ["Central"], 2)
underground.add_edge(barons_court, hammersmith, ["District", "Piccadilly"], 3)
underground.add_edge(bayswater, paddington, ["Circle", "District"], 2)
underground.add_edge(becontree, upney, ["District"], 2)
underground.add_edge(belsize_park, chalk_farm, ["Northern"], 2)
underground.add_edge(bermondsey, canada_water, ["Jubilee"], 2)
underground.add_edge(bethnal_green, mile_end, ["Central"], 2)
underground.add_edge(blackfriars, temple, ["Circle", "District"], 1)
underground.add_edge(blackhorse_road, tottenham_hale, ["Victoria"], 3)
underground.add_edge(bond_street, green_park, ["Jubilee"], 2)
underground.add_edge(bond_street, oxford_circus, ["Central"], 2)
underground.add_edge(borough, elephant_and_castle, ["Northern"], 2)
underground.add_edge(boston_manor, osterley, ["Piccadilly"], 3)
underground.add_edge(bounds_green, wood_green, ["Piccadilly"], 3)
underground.add_edge(brent_cross, golders_green, ["Northern"], 3)
underground.add_edge(bromley_by_bow, bow_road, ["District",  "Hammersmith and City"], 2)
underground.add_edge(bow_road, mile_end, ["District", "Hammersmith and City"], 2)
underground.add_edge(buckhurst_hill, loughton, ["Central"], 3)
underground.add_edge(burnt_oak, colindale, ["Northern"], 2)
underground.add_edge(caledonian_road, kings_cross_st_pancras, ["Piccadilly"], 4)
underground.add_edge(camden_town, euston, ["Northern"], 4)
underground.add_edge(camden_town, mornington_crescent, ["Northern"], 2)
underground.add_edge(canada_water, canary_wharf, ["Jubilee"], 3)
underground.add_edge(canary_wharf, north_greenwich, ["Jubilee"], 3)
underground.add_edge(canning_town, west_ham, ["Jubilee"], 3)
underground.add_edge(canons_park, queensbury, ["Jubilee"], 3)
underground.add_edge(cannon_street, mansion_house, ["Circle", "District"], 2)
underground.add_edge(chalfont_and_latimer, chorleywood, ["Metropolitan"], 4)
underground.add_edge(chalk_farm, camden_town, ["Northern"], 1)
underground.add_edge(chancery_lane, st_pauls, ["Central"], 2)
underground.add_edge(charing_cross, embankment, ["Bakerloo", "Northern"], 1)
underground.add_edge(chesham, chalfont_and_latimer, ["Metropolitan"], 9)
underground.add_edge(chigwell, roding_valley, ["Central"], 2)
underground.add_edge(chiswick_park, acton_town, ["District"], 2)
underground.add_edge(chorleywood, rickmansworth, ["Metropolitan"], 4)
underground.add_edge(clapham_common, clapham_south, ["Northern"], 2)
underground.add_edge(clapham_north, clapham_common, ["Northern"], 2)
underground.add_edge(clapham_south, balham, ["Northern"], 2)
underground.add_edge(cockfosters, oakwood, ["Piccadilly"], 2)
underground.add_edge(colindale, hendon_central, ["Northern"], 3)
underground.add_edge(colliers_wood, south_wimbeldon, ["Northern"], 2)
underground.add_edge(covent_garden, leicester_square, ["Piccadilly"], 1)
underground.add_edge(croxley, moor_park, ["Metropolitan"], 4)
underground.add_edge(east_ham, upton_park, ["District",  "Hammersmith and City"], 2)
underground.add_edge(dagenham_east, dagenham_heathway, ["District"], 2)
underground.add_edge(dagenham_heathway, becontree, ["District"], 3)
underground.add_edge(debden, theydon_bois, ["Central"], 3)
underground.add_edge(dollis_hill, willesden_green, ["Jubilee"], 2)
underground.add_edge(ealing_broadway, west_acton, ["Central"], 3)
underground.add_edge(ealing_common, ealing_broadway, ["District"], 5)
underground.add_edge(ealing_common, north_ealing, ["Piccadilly"], 2)
underground.add_edge(earls_court, barons_court, ["Piccadilly"], 3)
underground.add_edge(earls_court, kensington_olympia, ["District"], 3)
underground.add_edge(earls_court, west_kensington, ["District"], 2)
underground.add_edge(earls_court, high_street_kensington, ["District"], 5)
underground.add_edge(eastcoate, rayners_lane, ["Metropolitan", "Piccadilly"], 2)
underground.add_edge(east_acton, white_city, ["Central"], 3)
underground.add_edge(east_finchley, highgate, ["Northern"], 3)
underground.add_edge(east_putney, putney_bridge, ["District"], 3)
underground.add_edge(edgware, burnt_oak, ["Northern"], 4)
underground.add_edge(edgware_road, baker_street, ["Circle", "Hammersmith and City"], 3)
underground.add_edge(edgware_road, marylebone, ["Bakerloo"], 1)
underground.add_edge(elephant_and_castle, kennington, ["Northern"], 2)
underground.add_edge(elm_park, dagenham_east, ["District"], 3)
underground.add_edge(embankment, waterloo, ["Bakerloo", "Northern"], 2)
underground.add_edge(embankment, westminster, ["Circle", "District"], 1)
underground.add_edge(euston_square, kings_cross_st_pancras, ["Circle", "Hammersmith and City", "Metropolitan"], 2)
underground.add_edge(euston, kings_cross_st_pancras, ["Northern", "Victoria"], 2)
underground.add_edge(euston, warren_street, ["Northern"], 1)
underground.add_edge(euston, warren_street, ["Victoria"], 2)
underground.add_edge(great_portland_street, euston_square, ["Circle", "Hammersmith and City", "Metropolitan"], 2)
underground.add_edge(green_park, westminster, ["Jubilee"], 2)
underground.add_edge(hammersmith, ravenscourt_park, ["District"], 2)
underground.add_edge(fairlop, hainault, ["Central"], 2)
underground.add_edge(farringdon, barbican, ["Circle", "Hammersmith and City", "Metropolitan"], 1)
underground.add_edge(finchley_central, east_finchley, ["Northern"], 4)
underground.add_edge(finchley_road, baker_street, ["Metropolitan"], 5)
underground.add_edge(finchley_road, swiss_cottage, ["Jubilee"], 2)
underground.add_edge(finsbury_park, arsenal, ["Piccadilly"], 1)
underground.add_edge(finsbury_park, highbury_and_islington, ["Victoria"], 2)
underground.add_edge(fulham_broadway, west_brompton, ["District"], 2)
underground.add_edge(gants_hill, newbury_park, ["Central"], 3)
underground.add_edge(gloucester_road, earls_court, ["District", "Piccadilly"], 2)
underground.add_edge(gloucester_road, high_street_kensington, ["Circle"], 3)
underground.add_edge(golders_green, hampstead, ["Northern"], 4)
underground.add_edge(goldhawk_road, sheperds_bush_market, ["Circle", "Hammersmith and City"], 1)
underground.add_edge(goodge_street, tottenham_court_road, ["Northern"], 1)
underground.add_edge(grange_hill, chigwell, ["Central"], 2)
underground.add_edge(green_park, hyde_park_corner, ["Piccadilly"], 2)
underground.add_edge(green_park, victoria, ["Victoria"], 2)
underground.add_edge(greenford, perivale, ["Central"], 2)
underground.add_edge(gunnersby, kew_gardens, ["District"], 2)
underground.add_edge(hainault, grange_hill, ["Central"], 5)
underground.add_edge(hammersmith, goldhawk_road, ["Circle", "Hammersmith and City"], 2)
underground.add_edge(hammersmith, turnham_green, ["Piccadilly"], 4)
underground.add_edge(hampstead, belsize_park, ["Northern"], 3)
underground.add_edge(hanger_lane, north_acton, ["Central"], 3)
underground.add_edge(harlesden, willesden_junction, ["Bakerloo"], 2)
underground.add_edge(harrow_and_wealdstone, kenton, ["Bakerloo"], 2)
underground.add_edge(harrow_on_the_hill, northwick_park, ["Metropolitan"], 3)
underground.add_edge(hatton_cross, heathrow_terminals_2_and_3, ["Piccadilly"], 3)
underground.add_edge(hatton_cross, heathrow_terminal_4, ["Piccadilly"], 3)
underground.add_edge(heathrow_terminals_2_and_3, heathrow_terminal_5, ["Piccadilly"], 4)
underground.add_edge(heathrow_terminal_4, heathrow_terminals_2_and_3, ["Piccadilly"], 4)
underground.add_edge(hendon_central, brent_cross, ["Northern"], 2)
underground.add_edge(high_barnet, totteridge_and_whetstone, ["Northern"], 4)
underground.add_edge(high_street_kensington, notting_hill_gate, ["Circle", "District"], 2)
underground.add_edge(highbury_and_islington, kings_cross_st_pancras, ["Victoria"], 3)
underground.add_edge(highgate, archway, ["Northern"], 3)
underground.add_edge(hillingdon, ickenham, ["Metropolitan", "Piccadilly"], 2)
underground.add_edge(holborn, chancery_lane, ["Central"], 1)
underground.add_edge(holborn, covent_garden, ["Piccadilly"], 2)
underground.add_edge(holland_park, notting_hill_gate, ["Central"], 1)
underground.add_edge(holloway_road, caledonian_road, ["Piccadilly"], 2)
underground.add_edge(hornchurch, elm_park, ["District"], 2)
underground.add_edge(hounslow_central, hounslow_west, ["Piccadilly"], 3)
underground.add_edge(hounslow_east, hounslow_central, ["Piccadilly"], 1)
underground.add_edge(hounslow_west, hatton_cross, ["Piccadilly"], 4)
underground.add_edge(hyde_park_corner, knightsbridge, ["Piccadilly"], 2)
underground.add_edge(ickenham, ruislip, ["Metropolitan", "Piccadilly"], 2)
underground.add_edge(kennington, oval, ["Northern"], 3)
underground.add_edge(kennington, nine_elms, ["Northern"], 4)
underground.add_edge(kensal_green, queens_park, ["Bakerloo"], 2)
underground.add_edge(kentish_town, camden_town, ["Northern"], 2)
underground.add_edge(kenton, south_kenton, ["Bakerloo"], 2)
underground.add_edge(kew_gardens, richmond, ["District"], 4)
underground.add_edge(kilburn, west_hampstead, ["Jubilee"], 2)
underground.add_edge(kilburn_park, maida_vale, ["Bakerloo"], 2)
underground.add_edge(kings_cross_st_pancras, angel, ["Northern"], 3)
underground.add_edge(kings_cross_st_pancras, farringdon, ["Circle", "Hammersmith and City", "Metropolitan"], 4)
underground.add_edge(kings_cross_st_pancras, russell_square, ["Piccadilly"], 2)
underground.add_edge(kingsbury, wembley_park, ["Jubilee"], 3)
underground.add_edge(knightsbridge, south_kensington, ["Piccadilly"], 2)
underground.add_edge(ladbroke_grove, westbourne_park, ["Circle", "Hammersmith and City"], 2)
underground.add_edge(lambeth_north, elephant_and_castle, ["Bakerloo"], 3)
underground.add_edge(lancaster_gate, marble_arch, ["Central"], 3)
underground.add_edge(latimer_road, ladbroke_grove, ["Circle", "Hammersmith and City"], 2)
underground.add_edge(leicester_square, charing_cross, ["Northern"], 2)
underground.add_edge(leicester_square, piccadilly_circus, ["Piccadilly"], 1)
underground.add_edge(leyton, leytonstone, ["Central"], 2)
underground.add_edge(leytonstone, wanstead, ["Central"], 2)
underground.add_edge(liverpool_street, aldgate, ["Circle", "Metropolitan"], 3)
underground.add_edge(liverpool_street, aldgate_east, ["Hammersmith and City"], 3)
underground.add_edge(liverpool_street, bethnal_green, ["Central"], 3)
underground.add_edge(london_bridge, bermondsey, ["Jubilee"], 2)
underground.add_edge(london_bridge, borough, ["Northern"], 2)
underground.add_edge(loughton, debden, ["Central"], 2)
underground.add_edge(maida_vale, warwick_avenue, ["Bakerloo"], 1)
underground.add_edge(mansion_house, blackfriars, ["Circle", "District"], 2)
underground.add_edge(marble_arch, bond_street, ["Central"], 2)
underground.add_edge(marylebone, baker_street, ["Bakerloo"], 2)
underground.add_edge(manor_house, finsbury_park, ["Piccadilly"], 2)
underground.add_edge(monument, cannon_street, ["Circle", "District"], 1)
underground.add_edge(moorgate, liverpool_street, ["Circle", "Hammersmith and City", "Metropolitan"], 2)
underground.add_edge(mornington_crescent, euston, ["Northern"], 2)
underground.add_edge(neasden, dollis_hill, ["Jubilee"], 2)
underground.add_edge(mile_end, stepney_green, ["District", "Hammersmith and City"], 2)
underground.add_edge(mile_end, stratford, ["Central"], 4)
underground.add_edge(mill_hill_east, finchley_central, ["Northern"], 4)
underground.add_edge(moor_park, northwood, ["Metropolitan"], 3)
underground.add_edge(moorgate, bank, ["Northern"], 2)
underground.add_edge(newbury_park, barkingside, ["Central"], 2)
underground.add_edge(nine_elms, battersea_power_station, ["Northern"], 2)
underground.add_edge(north_acton, east_acton, ["Central"], 2)
underground.add_edge(north_ealing, park_royal, ["Piccadilly"], 2)
underground.add_edge(north_greenwich, canning_town, ["Jubilee"], 3)
underground.add_edge(north_harrow, harrow_on_the_hill, ["Metropolitan"], 3)
underground.add_edge(north_wembley, wembley_central, ["Bakerloo"], 2)
underground.add_edge(northolt, greenford, ["Central"], 2)
underground.add_edge(northfields, boston_manor, ["Piccadilly"], 2)
underground.add_edge(northwick_park, preston_road, ["Metropolitan"], 3)
underground.add_edge(northwood, northwood_hills, ["Metropolitan"], 3)
underground.add_edge(northwood_hills, pinner, ["Metropolitan"], 3)
underground.add_edge(notting_hill_gate, bayswater, ["Circle", "District"], 2)
underground.add_edge(notting_hill_gate, queensway, ["Central"], 2)
underground.add_edge(oakwood, southgate, ["Piccadilly"], 3)
underground.add_edge(old_street, moorgate, ["Northern"], 2)
underground.add_edge(osterley, hounslow_east, ["Piccadilly"], 2)
underground.add_edge(oval, stockwell, ["Northern"], 2)
underground.add_edge(oxford_circus, green_park, ["Victoria"], 2)
underground.add_edge(oxford_circus, piccadilly_circus, ["Bakerloo"], 2)
underground.add_edge(oxford_circus, tottenham_court_road, ["Central"], 1)
underground.add_edge(regents_park, oxford_circus, ["Bakerloo"], 2)
underground.add_edge(roding_valley, woodford, ["Central"], 4)
underground.add_edge(paddington, edgware_road, ["Bakerloo"], 2)
underground.add_edge(paddington, edgware_road, ["Circle", "District", "Hammersmith and City"], 3)
underground.add_edge(park_royal, alperton, ["Piccadilly"], 2)
underground.add_edge(parsons_green, fulham_broadway, ["District"], 2)
underground.add_edge(perivale, hanger_lane, ["Central"], 3)
underground.add_edge(piccadilly_circus, embankment, ["Bakerloo"], 2)
underground.add_edge(piccadilly_circus, green_park, ["Piccadilly"], 2)
underground.add_edge(pimlico, vauxhall, ["Victoria"], 2)
underground.add_edge(pinner, north_harrow, ["Metropolitan"], 2)
underground.add_edge(plaistow, west_ham, ["District", "Hammersmith and City"], 2)
underground.add_edge(preston_road, wembley_park, ["Metropolitan"], 3)
underground.add_edge(putney_bridge, parsons_green, ["District"], 3)
underground.add_edge(queens_park, kilburn_park, ["Bakerloo"], 2)
underground.add_edge(queensbury, kingsbury, ["Jubilee"], 2)
underground.add_edge(queensway, lancaster_gate, ["Central"], 2)
underground.add_edge(ravenscourt_park, stamford_brook, ["District"], 2)
underground.add_edge(rayners_lane, west_harrow, ["Metropolitan"], 3)
underground.add_edge(redbridge, gants_hill, ["Central"], 2)
underground.add_edge(regents_park, oxford_circus, ["Bakerloo"], 2)
underground.add_edge(rickmansworth, moor_park, ["Metropolitan"], 5)
underground.add_edge(royal_oak, paddington, ["Circle", "Hammersmith and City"], 2)
underground.add_edge(ruislip, ruislip_manor, ["Metropolitan", "Piccadilly"], 2)
underground.add_edge(ruislip_gardens, south_ruislip, ["Central"], 2)
underground.add_edge(ruislip_manor, eastcoate, ["Metropolitan", "Piccadilly"], 2)
underground.add_edge(russell_square, holborn, ["Piccadilly"], 2)
underground.add_edge(seven_sisters, finsbury_park, ["Victoria"], 5)
underground.add_edge(shepherds_bush, holland_park, ["Central"], 2)
underground.add_edge(sheperds_bush_market, wood_lane, ["Circle", "Hammersmith and City"], 2)
underground.add_edge(sloane_square, south_kensington, ["Circle", "District"], 2)
underground.add_edge(snaresbrook, south_woodford, ["Central"], 2)
underground.add_edge(south_harrow, rayners_lane, ["Piccadilly"], 5)
underground.add_edge(south_kensington, gloucester_road, ["Circle", "District", "Piccadilly"], 3)
underground.add_edge(south_kenton, north_wembley, ["Bakerloo"], 2)
underground.add_edge(south_ruislip, northolt, ["Central"], 3)
underground.add_edge(south_wimbeldon, morden, ["Northern"], 3)
underground.add_edge(south_woodford, woodford, ["Central"], 3)
underground.add_edge(southgate, arnos_grove, ["Piccadilly"], 4)
underground.add_edge(southfields, east_putney, ["District"], 2)
underground.add_edge(southwark, london_bridge, ["Jubilee"], 2)
underground.add_edge(stamford_brook, turnham_green, ["District"], 1)
underground.add_edge(stanmore, canons_park, ["Jubilee"], 4)
underground.add_edge(sudbury_hill, south_harrow, ["Piccadilly"], 3)
underground.add_edge(sudbury_town, sudbury_hill, ["Piccadilly"], 2)
underground.add_edge(st_james_park, victoria, ["Circle", "District"], 2)
underground.add_edge(st_johns_wood, baker_street, ["Jubilee"], 3)
underground.add_edge(st_pauls, bank, ["Central"], 2)
underground.add_edge(stratford, leyton, ["Central"], 3)
underground.add_edge(stepney_green, whitechapel, ["District",  "Hammersmith and City"], 3)
underground.add_edge(stockwell, brixton, ["Victoria"], 2)
underground.add_edge(stockwell, clapham_north, ["Northern"], 2)
underground.add_edge(stonebridge_park, harlesden, ["Bakerloo"], 2)
underground.add_edge(south_ealing, northfields, ["Piccadilly"], 1)
underground.add_edge(swiss_cottage, st_johns_wood, ["Jubilee"], 2)
underground.add_edge(temple, embankment, ["Circle", "District"], 2)
underground.add_edge(theydon_bois, epping, ["Central"], 3)
underground.add_edge(tooting_bec, tooting_broadway, ["Northern"], 2)
underground.add_edge(tooting_broadway, colliers_wood, ["Northern"], 2)
underground.add_edge(tottenham_court_road, leicester_square, ["Northern"], 2)
underground.add_edge(tottenham_court_road, holborn, ["Central"], 2)
underground.add_edge(tottenham_hale, seven_sisters, ["Victoria"], 2)
underground.add_edge(totteridge_and_whetstone, woodside_park, ["Northern"], 2)
underground.add_edge(tower_hill, monument, ["Circle", "District"], 2)
underground.add_edge(tufnell_park, kentish_town, ["Northern"], 1)
underground.add_edge(turnham_green, acton_town, ["Piccadilly"], 4)
underground.add_edge(turnham_green, chiswick_park, ["District"], 2)
underground.add_edge(turnham_green, gunnersby, ["District"], 3)
underground.add_edge(turnpike_lane, manor_house, ["Piccadilly"], 4)
underground.add_edge(upminster, upminster_bridge, ["District"], 2)
underground.add_edge(upminster_bridge, hornchurch, ["District"], 2)
underground.add_edge(upney, barking, ["District"], 3)
underground.add_edge(upton_park, plaistow, ["District",  "Hammersmith and City"], 2)
underground.add_edge(uxbridge, hillingdon, ["Metropolitan", "Piccadilly"], 4)
underground.add_edge(vauxhall, stockwell, ["Victoria"], 3)
underground.add_edge(victoria, pimlico, ["Victoria"], 2)
underground.add_edge(victoria, sloane_square, ["Circle", "District"], 2)
underground.add_edge(walthamstow_central, blackhorse_road, ["Victoria"], 3)
underground.add_edge(wanstead, redbridge, ["Central"], 2)
underground.add_edge(wanstead, snaresbrook, ["Central"], 2)
underground.add_edge(warren_street, goodge_street, ["Northern"], 2)
underground.add_edge(warren_street, oxford_circus, ["Victoria"], 2)
underground.add_edge(warwick_avenue, paddington, ["Bakerloo"], 1)
underground.add_edge(waterloo, lambeth_north, ["Bakerloo"], 2)
underground.add_edge(waterloo, kennington, ["Northern"], 3)
underground.add_edge(waterloo, southwark, ["Jubilee"], 2)
underground.add_edge(watford, croxley, ["Metropolitan"], 4)
underground.add_edge(wembley_central, stonebridge_park, ["Bakerloo"], 3)
underground.add_edge(wembley_park, neasden, ["Jubilee"], 4)
underground.add_edge(wembley_park, finchley_road, ["Metropolitan"], 7)
underground.add_edge(west_acton, north_acton, ["Central"], 2)
underground.add_edge(west_brompton, earls_court, ["District"], 2)
underground.add_edge(west_finchley, finchley_central, ["Northern"], 2)
underground.add_edge(west_ham, stratford, ["Jubilee"], 3)
underground.add_edge(west_ham, bromley_by_bow, ["District",  "Hammersmith and City"], 2)
underground.add_edge(west_hampstead, finchley_road, ["Jubilee"], 1)
underground.add_edge(west_harrow, harrow_on_the_hill, ["Metropolitan"], 2)
underground.add_edge(west_kensington, barons_court, ["District"], 2)
underground.add_edge(west_ruislip, ruislip_gardens, ["Central"], 2)
underground.add_edge(westbourne_park, royal_oak, ["Circle", "Hammersmith and City"], 2)
underground.add_edge(westminster, st_james_park, ["Circle", "District"], 2)
underground.add_edge(westminster, waterloo, ["Jubilee"], 2)
underground.add_edge(white_city, shepherds_bush, ["Central"], 3)
underground.add_edge(whitechapel, aldgate_east, ["District",  "Hammersmith and City"], 2)
underground.add_edge(willesden_green, kilburn, ["Jubilee"], 2)
underground.add_edge(willesden_junction, kensal_green, ["Bakerloo"], 3)
underground.add_edge(wimbeldon, wimbeldon_park, ["District"], 4)
underground.add_edge(wimbeldon_park, southfields, ["District"], 2)
underground.add_edge(wood_green, turnpike_lane, ["Piccadilly"], 2)
underground.add_edge(wood_lane, latimer_road, ["Circle", "Hammersmith and City"], 2)
underground.add_edge(woodford, buckhurst_hill, ["Central"], 2)
underground.add_edge(woodside_park, west_finchley, ["Northern"], 2)


#Remove edges from Heathrow Terminals to account for one-way loop
heathrow_terminals_2_and_3.edges.pop("Heathrow Terminal 4")
heathrow_terminal_4.edges.pop("Hatton Cross")